#### `Ali Almalki`
Let's cook up some PyTorch code👨🏻‍🍳

### 1. Perform standard imports
Import torch and NumPy

In [16]:
# CODE HERE

import torch 
import numpy as np

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [17]:
# CODE HERE

# np.random.seed(42)
# np.random.rand(2,3)

torch.manual_seed(42)
x = np.random.rand(3,2)
torch.tensor(x)


tensor([[0.6075, 0.1705],
        [0.0651, 0.9489],
        [0.9656, 0.8084]], dtype=torch.float64)

### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [18]:
# CODE HERE
arr = np.random.randint(0,5,6)
arr


array([0, 1, 4, 1, 3, 3])

In [ ]:
# DON'T WRITE HERE

[3 4 2 4 4 1]


### 4. Create a tensor "x" from the array above

In [20]:
# CODE HERE

x = torch.from_numpy(arr)
x

tensor([0, 1, 4, 1, 3, 3])

In [ ]:
# DON'T WRITE HERE

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [25]:
# CODE HERE

x.type('torch.LongTensor')
type(x)


torch.Tensor

In [ ]:
# DON'T WRITE HERE

torch.LongTensor


### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [30]:
# CODE HERE

# x.reshape(3,2)
# torch.reshape(x, (3,2))
# x = x.reshape(3,2)
# x.resize_(3,2)
x = x.view(3,2)
x

tensor([[0, 1],
        [4, 1],
        [3, 3]])

In [ ]:
# DON'T WRITE HERE

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Return the right-hand column of tensor x

In [31]:
# CODE HERE
x[:, 1:]


tensor([[1],
        [1],
        [3]])

In [ ]:
# DON'T WRITE HERE

tensor([[4],
        [4],
        [1]])


### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [33]:
# CODE HERE

# torch.square(x)
# print(x**2)
# print(x.mul(x))
# print(x.pow(2))
# print(torch.mul(x,x))

print(x*x)

tensor([[ 0,  1],
        [16,  1],
        [ 9,  9]])


In [ ]:
# DON'T WRITE HERE

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [42]:
x.shape

torch.Size([3, 2])

In [43]:
# CODE HERE


y = torch.randint(0,5,(2,3))
print(y)

tensor([[4, 3, 1],
        [4, 2, 4]])


In [ ]:
# DON'T WRITE HERE

tensor([[2, 2, 1],
        [4, 1, 0]])


### 10. Find the matrix product of x and y

In [44]:
print(x)
print(y)

tensor([[0, 1],
        [4, 1],
        [3, 3]])
tensor([[4, 3, 1],
        [4, 2, 4]])


In [48]:
# CODE HERE

torch.matmul(x, y)
#x.mm(y)


tensor([[ 4,  2,  4],
        [20, 14,  8],
        [24, 15, 15]])

In [ ]:
# DON'T WRITE HERE

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


### References: 

* [NumPy Documentation](https://numpy.org/doc/stable/)

* [PyTorch Documentation](https://pytorch.org/docs/stable/index.html)

* [Exercise Creator](https://pieriantraining.com)